project:
  type: website
  output-dir: _site

website:
  title: "Children's Songbook"
  navbar:
    left:
      - text: Home
        href: index.qmd

format:
  html:
    theme: cosmo
    toc: false
    css: songbook.css
    include-in-header:
    - text: |
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Fira+Mono:wght@400;700&display=swap" rel="stylesheet">

filters:
  - chordify.lua