---
title: "Can you say, How do you do?"
description: ""
page-layout: article
---
<div class="song">

*(Capo 3)*

1  
[G] Can you say, "How do you do, do you do, do you do?"  
[G] Can you say, "How do you [Em] do, how do you [Am] do?" [D]  
We can [Am7] say, "How do you [D7] do?"  and "I'm just [G] fine and how are you?"  
[C] We can [G] say, "How [Em] do you [Am7] do,  [D7] do you [G] do?" [C/D]  

2   
Can you give a hand a shake, hand a shake, hand a shake?  
Can you give a hand a shake, hand a shake?  
We can smile and give a shake, a new friend then we will make,  
We can give a hand a shake, hand a shake.  

3  
Can you look 'em in the eye, in the eye, in the eye?  
Can you look 'em in the eye, in the eye?  
We can look 'em in the eye, not the floor and not the sky!  
We can look 'em in the eye, in the eye.  

4   
Can you greet with, "Buenos dias, buenos dias, buenos dias",  
Can you greet with "Buenos dias, buenos dias."  
We can greet with "Buenos dias, we're so glad you came to see us!"  
We can greet with "Buenos dias, buenos dias."  

5  
Can you bow bending low and say, "Ahn nyeong hasayo?"  
Can you bow low and say, "Ahn nyeong hasayo?"  
We can bow bending low and say, "Ahn nyeong hasayo!"  
To Koreans we say, "Ahn nyeong hasayo."  

6
Can you nod and say, "Nee how," say, "Nee how,"say, "Nee how,"  
Can you nod and say, "Nee how," say, "Nee how."  
We can nod and say, "Nee how;" They'll say, "You know Chinese, WOW!"  
We can nod and say, "Nee how," say, "Nee how."

https://www.hymnal.net/en/hymn/c/10


</div>
