---
title: "Take Twelve Stones Out"
format: html
---

<div class="song">


[D] Take twelve stones out, [G] for a me- [A] morial.   
[D] Take twelve stones out, one [G] stone for every [A] tribe. 
[D] Take  twelve stones out, [G] then shall your [A] children know.   
[D] Israel came [G] over [Em] Jordan [A] marching on dry [D] land.


What do these stones mean? Israel had chosen God.  
What do these stones mean? A new life they’d begun.  
What do these stones mean? That they would not turn back.  
They’re God’s testimony living in the promised land.


> When the [G] priest’s feet touched the river [D] Jordan,  
> The [Bm] waters were blocked from a [A] way off.  
> And the [G] riverbed was dry that the [D] people,  
> Could [Em] pass over [A] on dry [A7] land.


Put twelve stones in, for a memorial.  
Put twelve stones in, to stay in Jordan’s flow.  
Put twelve stones in, old life had passed away.  
No more life of wandering, we have entered the good land.

> When the priest’s feet touched the river Jordan,  
> The waters were blocked from a way off.  
> And the riverbed was dried that the people,  
> Could pass over on dry land.

Take twelve stones out, for a memorial.  
Take twelve stones out, one stone for every tribe.  
Take twelve stones out, then shall your children know.  
Israel came over Jordan marching on dry land.

</div>
